In [2]:
import numpy as np

In [4]:
import numpy as np

# np.array is used to create an array

arr1=np.array([1,2])
arr2=np.array([4,5])

result = arr1+arr2

result

array([5, 7])

In [6]:
# Different ways to initialize some array

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# below code is used to check the number of dimensions in the array

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
# Used to initialize a 5-D array

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
# Indexing in the array

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [10]:
# Adding elements in the array

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [11]:

# Accessing 2-D arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [12]:
# Accessing 3-D arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [14]:
# Slicing in the arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[1 3 5 7]


In [15]:
# Checking the datatypes of an array

arr = np.array([1, 2, 3, 4])
arr1 = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
print(arr1.dtype)

int64
<U6


In [16]:
# Changes made in a view affects the original array

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [17]:
# Changes made to the copy will not affect the original array

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [18]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [3]:
# Shape of an array is the number of elements in each dimension

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [2]:
# We can iterate through the arrays using for loop

arr = np.array([1, 2, 3])
print('Iterating in 1-D')
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Iterating in 2-D')
for x in arr:
  print(x)

1
2
3
[1 2 3]
[4 5 6]


In [3]:
# Joining arrays using concatenate

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [9]:
# Joining through stack functions

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
# Stacking along Rows

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [14]:
# Stacking along columns

arr1 = np.array([1, 2, 3,8])

arr2 = np.array([4, 5, 6,7])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3 8]
 [4 5 6 7]]


In [19]:
# Splitting Arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [21]:
# Splitting into Arrays

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[1 2]
[3 4]
[5]
[6]


In [25]:
# Searching an array for a value and returning the indexes

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int32),)


In [26]:
# Searching for even numbers in an array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int32),)


In [27]:
# Sorting arrays using sort function

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [28]:
# Filtering - Getting some elements out of an existing array and creating a new array out of them

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [29]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
